
TYPE
	providePellet_CaseEnum : 
		( (* Operational States *)
		PELLET_SUPPLY_DECISION_CASE,
		PLTSUP_INTERMPOS1_CASE,
		PLTSUP_INTERMPOS2_CASE,
		PELLET_SUPPLY_BEFORE_SMALL_CASE,
		PELLET_SUPPLY_SMALL_CASE,
		PELLET_SUPPLY_TIMER_CASE,
		PELLET_SUPPLY_BIG_CASE,
		PLTSUP_INTERMPOS1END_CASE,
		PLTSUP_INTERMPOS2END_CASE,
		PELLET_SUPPLY_FINAL_CASE,
		PELLET_SUPPLY_FINAL_CASE1
		);
	provideCup_CaseEnum : 
		( (* Operational States *)
		CUP_SUPPLY_DECISION_CASE,
		PLASTIC_CUP_SAFE_POSITION_CASE,
		PLASTIC_CUP_ABOVE_POSITION_CASE,
		PLASTIC_CUP_POSITION_CASE,
		PLASTIC_CUP_TIMER_CASE,
		PLASTIC_CUP_ABOVE_POSITION_CASE1,
		PLASTIC_CUP_SAFE_POSITION_CASE1,
		PAPER_CUP_SAFE_POSITION_CASE,
		PAPER_CUP_ABOVE_POSITION_CASE,
		PAPER_CUP_POSITION_CASE,
		PAPER_CUP_TIMER_CASE,
		PAPER_CUP_ABOVE_POSITION_CASE1,
		PAPER_CUP_SAFE_POSITION_CASE1,
		SUPERTRAK_ABOVE_POSITION_CASE,
		SUPERTRAK_POSITION_CASE,
		SUPERTRAK_TIMER_CASE,
		SUPERTRAK_ABOVE_POSITION_CASE1,
		SAFE_POSITION_CASE,
		CUP_SUPPLY_FINAL_CASE,
		CUP_SUPPLY_FINAL_CASE1
		);
	Clearing_CaseEnum : 
		(
		POWERON,
		HOMING,
		EXIT_CLEARING
		);
	Stopped_CaseEnum : 
		(
		GENERAL_STOPPED,
		HOMING_STOPPED,
		EXIT_HOMING_STOPPED,
		MAINTENANCE_STOPPED
		);
END_TYPE
