(*                                                                            *)
(* File generated by the B&R AS 4 control config generator                    *)
(*                                                                            *)
(*     Provider: machineering                                                 *)
(*  Application: industrialPhysics                                            *)
(* Architecture: Windows 64 Bit                                               *)
(*      Version: 2.2.8481.master                                              *)
(*        Build: 057354c2a                                                    *)
(*         Date: 2020-02-28, Time: 15:09:14                                   *)
(*                                                                            *)

TYPE
    (* 3d position *)
    VEC3 : STRUCT
                    x: REAL;
                    y: REAL;
                    z: REAL;
    END_STRUCT;

    (* position and orientation as an euler based pose *)
    POSE6 :	STRUCT
                    x: REAL;
                    y: REAL;
                    z: REAL;
                    a: REAL;
                    b: REAL;
                    c: REAL;
    END_STRUCT;

    (* position and orientation as a 4x4 matrix *)
    TRAFO :STRUCT
                    baseX : VEC3;
                    fill0 : REAL;
                    baseY : VEC3;
                    fill1 : REAL;
                    baseZ : VEC3;
                    fill2 : REAL;
                    origin : VEC3;
                    fill3 : REAL;
    END_STRUCT;

                MNG_APPLICATION_INPUTS_32BIT : STRUCT
    NumSignals                    : INT     := 3         ;
    Gripper01_VACUUM                : BOOL    := 0; (* omau_Link5_Comau_Link6_Gripper_Comau_Gripper?Vacuum *)
    PaperCupDrawer01_IsOpened       : BOOL    := 0; (* embly_Module_PaperCupSupply_PaperCupDrawer?IsOpened *)
    PlasticCupDrawer01_IsOpened     : BOOL    := 0; (* y_Module_PlasticCupSupply_PlasticCupDrawer?IsOpened *)
END_STRUCT;
MNG_APPLICATION_OUTPUTS_32BIT : STRUCT
    NumSignals                    : INT     := 9         ;
    Comau_Link101_TGT_POS           : REAL    := 0.0; (* _Assembly_Module_Comau_Racer3_Comau_Link1?KinTarget *)
    Comau_Link201_TGT_POS           : REAL    := 0.0; (* dule_Comau_Racer3_Comau_Link1_Comau_Link2?KinTarget *)
    Comau_Link301_TGT_POS           : REAL    := 0.0; (* acer3_Comau_Link1_Comau_Link2_Comau_Link3?KinTarget *)
    Comau_Link401_TGT_POS           : REAL    := 0.0; (* Link1_Comau_Link2_Comau_Link3_Comau_Link4?KinTarget *)
    Comau_Link501_TGT_POS           : REAL    := 0.0; (* Link2_Comau_Link3_Comau_Link4_Comau_Link5?KinTarget *)
    Comau_Link601_TGT_POS           : REAL    := 0.0; (* Link3_Comau_Link4_Comau_Link5_Comau_Link6?KinTarget *)
    Gripper01_GRIP                  : BOOL    := 0; (* mau_Link5_Comau_Link6_Gripper_Comau_Gripper?Gripper *)
    PaperCupDrawer01_Assem          : BOOL    := 0; (* ssembly_Module_PaperCupSupply_PaperCupDrawer?_Assem *)
    PlasticCupDrawer01_Assem        : BOOL    := 0; (* bly_Module_PlasticCupSupply_PlasticCupDrawer?_Assem *)
END_STRUCT;

END_TYPE
        